version: "3.9"

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=dps_db
      - POSTGRES_USER=vadim
      - POSTGRES_PASSWORD=vadim
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5436:5432"

volumes:
  db: